### ISSUE TITLE
Wrong time complexity in README and crate documentation.

### ISSUE THREAD

**Issue by smarnach** [thomwiggers/factorial#3]
Both the README and the crate documentation state

> This crate provides some convenient and safe methods to compute the factorial and related functions in O(n) time.
>
> They are not necessarily the fastest versions: there are prime sieve methods that compute the factorial in `O(n (log n loglog n)^2)`. Patches are welcome.

The claimed time complexity of O(n) would actually be _faster_ than the fastest known algorithm. This crate seems to implement a naive approach, which has time complexity that depends on the multiplication algorithm that is used. With the Toom-3 implementation in `num_bigint`, we should get something like O(n^2.46 log(n)), but that's not likely to be useful information for most people, so I suggest to simply omit the time complexity in favour of stating that this crate implements a naive approach.

**Comment by thomwiggers** [comment]
You're right, but the complexity is _also_ O(n), where O(n) is the number of multiplications. Of course, those indeed aren't O(1) for bigint. The given complexity for prime sieves (probably copied off Wikipedia) probably includes (some of) those costs.

**Comment by smarnach** [comment]
Yes, the number of multiplications performed is O(n), but the time complexity definitely isn't. The time complexity describes an asymptotical upper limit for the runtime of the function as n approaches infinity, and that necessarily needs to take into account the time of a multiplication.
