### ISSUE TITLE
Double factorial implementation is incorrect

### ISSUE THREAD

**Issue by al2me6** [thomwiggers/factorial#6]
This implementation produces incorrect results for odd numbers. For example, `7!! = 105`, while this crate gives `48`. It appears that

https://github.com/thomwiggers/factorial/blob/3b33d3e971f771b60f8151aae57db824600d9292/src/lib.rs#L75-L79

leads to the erroneous computation of `7!! = 2 * 4 * 6`, while the correct computation is `7!! = 7 * 5 * 3 * 1`.

**Comment by thomwiggers** [comment]
I've fixed this via the implementation from #5. I've also pushed 0.2.1 to Crates.io.
